source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'devise'
gem 'haml-rails'
gem "compass", ">= 0.10.5"
gem "jquery-rails"
gem 'hpricot'
gem 'ruby_parser'

group :development, :test do
  gem "rspec-rails", ">= 2.0.0.beta.22"
  gem 'cucumber-rails'
  gem 'webrat'
  gem 'ruby-debug'
end
